variables:
  MAIN_IMAGE: registry.gitlab.com/codewithakay42/reactresume

stages:
  - build
  - deploy_to_s3
  - deploy_to_lambda

.install_python_packages:
  script:

app_build:
  stage: build
  image: $MAIN_IMAGE
  script:
    - cd frontend
    - npm i
    - npm run build
    - pwd
    # TODO Find the ViteJS solution for this!!
    - sed -i '' 's/<title>.*<\/title>/<title>Code With a K<\/title>/' index.html
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - dist/
  tags:
    - docker

deploy_website:
  extends: .install_python_packages
  stage: deploy_to_s3
  image: $MAIN_IMAGE
  script:
    - pip install -r requirements.txt
    - python deploy_website.py
  dependencies:
    - app_build
  tags:
    - docker

deploy_mail_server:
  extends: .install_python_packages
  stage: deploy_to_lambda
  image: $MAIN_IMAGE
  script:
    - pip install -r requirements.txt
    - python deploy_mail_server.py
  tags:
    - docker
  only:
    refs:
      - main