stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/codewithakay42/reactresume
  script:
    - cd frontend
    - npm i
    - npm run build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - dist/
  tags:
    - docker

deploy:
  stage: deploy
  image: registry.gitlab.com/codewithakay42/reactresume  # Use the same image with Python and AWS CLI
  script:
    - echo 'Deploying to S3 bucket'
  dependencies:
    - build
  tags:
    - docker