stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/codewithakay42/reactresume
  script:
    - cd frontend
    - npm i
    - npm run build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - dist/
  tags:
    - docker

deploy:
  stage: deploy
  image: registry.gitlab.com/codewithakay42/reactresume  # Use the same image with Python and AWS CLI
  script:
    - cd frontend
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - if ! aws s3 ls s3://$AWS_S3_RESUME_BUCKET_NAME; then aws s3 mb s3://$AWS_S3_RESUME_BUCKET_NAME; fi
    - aws s3 sync dist/ s3://$AWS_S3_RESUME_BUCKET_NAME/
  dependencies:
    - build
  tags:
    - docker