stages:
  - build
  - deploy_to_s3
  - deploy_to_lambda

build:
  stage: build
  image: registry.gitlab.com/codewithakay42/reactresume
  script:
    - cd frontend
    - npm i
    - npm run build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - dist/
  tags:
    - docker

deploy:
  stage: deploy_to_s3
  image: registry.gitlab.com/codewithakay42/reactresume  # Use the same image with Python and AWS CLI
  script:
    - pip install -r requirements.txt
    - pwd
    - python cicd/deploy_website.py
  dependencies:
    - build
  tags:
    - docker