stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/codewithakay42/reactresume
  script:
    - npm ci
    - npm run build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - dist/
  tags:
    - docker