variables:
  MAIN_IMAGE: registry.gitlab.com/codewithakay42/reactresume

stages:
  - build
  - deploy_to_s3
  - deploy_to_lambda

app_build:
  stage: build
  image: $MAIN_IMAGE
  script:
    - echo $AWS_API_GATEWAY_URL
    - cd frontend
    - npm i
    - npm run build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - dist/
  tags:
    - docker

deploy_website:
  stage: deploy_to_s3
  image: $MAIN_IMAGE
  script:
    - pip install -r requirements.txt
    - python deploy_website.py
  dependencies:
    - app_build
  tags:
    - docker

deploy_mail_server:
  stage: deploy_to_lambda
  image: $MAIN_IMAGE
  script:
    - pip install -r requirements.txt
    - python deploy_mail_server.py
  tags:
    - docker
  only:
    refs:
      - main